Read from file, check invalid

diff --git a/.github/workflows/external-code-affected.yml b/.github/workflows/external-code-affected.yml
--- a/.github/workflows/external-code-affected.yml
+++ b/.github/workflows/external-code-affected.yml
@@ -22,15 +22,23 @@ jobs:
       id: checkfile
       run: |
         set -xe
+        file_pattern="^[-a-zA-Z0-9_\/.]*$"
+        uri_pattern="^https?://[a-zA-Z0-9-._:/&#]+"
+
         declare -A FILES_TO_EXTERNAL_URI
-        FILES_TO_EXTERNAL_URI=(
-          # This is a mapping from [source_code_file] --> [external URI]
-          # When `source_code_file` is changed, the `external URI` should be reviewed.
-          ["src/tracked_file.py"]="https://github.com/ray-project/ray/somewhere"
-          ["src/second_tracked_file.py"]="https://github.com/ray-project/ray/else"
-          # Add more fils below.
-        )
+        while read -r line; do
+          file=$(echo $line | cut -d' ' -f1)
+          uri=$(echo $line | cut -d' ' -f2)
         
+          # Check that these conform to expected patterns
+          if ! [[ $file =~ $file_pattern && $uri =~ $uri_pattern ]]; then
+            echo "Invalid file path or URI detected: $line"
+            exit 1
+          fi
+        
+          FILES_TO_EXTERNAL_URI["$file"]="$uri"
+        done < external_code.txt
+
         CHANGED_FILES_URIS=""
         GIT_DIFF=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
         
